07-Django-and-Templates/01-Filters-and-Tags/my_site/my_app/urls.py
from django.urls import path
from . import views

# Register the app namespace
app_name = 'my_app'

urlpatterns = [
    path('', views.example_view,name='home'),
    path('filters/',views.filter_view)
]

07-Django-and-Templates/01-Filters-and-Tags/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/',include('my_app.urls'))
]

07-Django-and-Templates/01-Filters-and-Tags/my_site/my_app/models.py
from django.db import models

# Create your models here.

07-Django-and-Templates/01-Filters-and-Tags/my_site/my_app/views.py
from django.shortcuts import render

# Create your views here.
def example_view(request):
    # python manage.py migrate
    # check apps.py file inside my_app
    # confirm Config class is there
    # add Config to INSTALLED_APPS ('my_app.apps.MyAppConfig')
    # python manage.py makemigrations my_app (result is No changes detected in app 'my_app')
    # python manage.py migrate (no migrations to apply)
    # create my_app/templates/my_app/home.html
    return render(request,'my_app/home.html')

def filter_view(request):

    # MUST BE A DICTIONARY
    my_var = {'first_name':'Rosalind','last_name':'Franklin',
               'some_list':[1,2,3],'some_dict':{'inside_key':'inside_value'}}


    return render(request,'my_app/filters.html',context=my_var)

07-Django-and-Templates/01-Filters-and-Tags/my_site/my_app/templates/my_app/filters.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    {% comment %} https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#ref-templates-builtins-filters {% endcomment %}
    <h1>{{first_name | upper}}</h1>
    {% comment %} TAGS {% endcomment %}
    {% lorem %}
    <h1>{% now "jS \o\f F" %}</h1>

    {% comment %}  {% endcomment %}
    <ul>
    {% for item in some_list  %}
    
        <li>{{item}}</li>
    
    {% endfor %}
</ul>


   {% comment %}  {% endcomment %}
   <ul>
    {% for item in some_list  %}

    {% if item == 2 %}
       <p>if statement triggered</p>
    
    {% endif %}
    
        <li>{{item}}</li>
    
    {% endfor %}
</ul>

  {% comment %}  {% endcomment %}
  <ul>
    {% for item in some_list  %}

    {% if item == 2 %}
       <li>TWO</li>
       {% else %}
       <li>{{item}}</li>
    {% endif %}
    
       
    
    {% endfor %}
</ul>
    
<h1><a href="{% url 'my_app:home' %}">HOME</a></h1>
    
</body>
</html>

07-Django-and-Templates/01-Filters-and-Tags/my_site/my_app/templates/my_app/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This is home.html inside my_app/templates/my_app</h1>
</body>
</html>